### ISSUE TITLE
Home page improvements

### ISSUE THREAD

**Issue by dionisisvas** [dionisisvas/training-project#100]
As a user I would like to see a nice dashboard-like home page to access the application from.

Some improvements are suggested to be done in the homepage of the application to enhance the user experience:
* Large icons should be a added in the place of the links on the first list
* Rest endpoint list should be accessible from a different button on the menu on the left

**Comment by chris-iri** [comment]
About the first bullet point: Most of the links are added on the sidenav; registration & login are missing because I was hoping to redirect the user to them (and hide the sidenav) if he isn't logged in. I haven't implemented it yet because of #81. However, since the auth cookie is working, I could probably do it on the front-end and leave the back-end access blocking for later.

**Comment by dionisisvas** [comment]
As a workaround for the blocker bug #81 this sounds good. If you have a better idea to "beautify" the homepage rather than adding icons please proceed as you like
